package uiComponents.UpdateItemsGui.RemoveItemsFromStoreGui;
////uiComponents.UpdateItemsGui.RemoveItemsFromStoreGui.RemoveItemsFromStoreGuiController
public class RemoveItemsFromStoreGuiController {
}
